### DISCUSSION TITLE
Preview missing for Spotbugs issues in GitHub Code Scanning Alerts

### DISCUSSION THREAD

**Discussion by hmmh-sven-scheil** [spotbugs/spotbugs#3081] [Q&A]
Hello,

I've integrated SpotBugs in my build.gradle file. SpotBugs exports a report in sarif-format. My Github Pipeline uploads this report to code scanning, using this action

```
    - name: Upload SARIF file
      uses: github/codeql-action/upload-sarif@v3
      with:
          # Path to SARIF file relative to the root of the repository
          sarif_file: "build/reports/spotbugs.sarif"
          # Optional category for the results
          # Used to differentiate multiple results for one commit
          category: SpotBugs
``` 

The SpotBug findings are shown  in GitHub Code Scanning Alerts, but there is no preview available and no direct link to the file in the repo. I don't understand what do change, so I get at least a link to the location in the code where the issue was fount.
